# Rarity for House - Raridade para Casa
# rarity: ["common", "rare", "super_rare", "epic", "legend", "super_legend"]

1: {
    mode: "amazon_survival", # amazon_survival
    username: "",
    password: "",
    house: false,
    rarity: [],
  }
